-- generated by `arc psqldb migrate` for plugin 'filer'

-- (schema) ensure audit table "_audit_filer" exists

        CREATE TABLE IF NOT EXISTS "_audit_filer" (
            id          UUID PRIMARY KEY DEFAULT arc_uuid_generate_v7(),
            "table"     TEXT NOT NULL,
            row_id      UUID NOT NULL,
            changes     JSONB NOT NULL,
            changed_by  TEXT,
            changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        ;

        CREATE OR REPLACE FUNCTION arc_audit_filer() RETURNS trigger AS $$
        DECLARE
            new_json jsonb := to_jsonb(NEW);
            old_json jsonb := to_jsonb(OLD);
        BEGIN
            -- changed_by goes through the jsonb representation, not a direct
            -- NEW.updated_by/OLD.updated_by struct reference: this function is
            -- shared across every audited table for the plugin, and a
            -- "system": true table (psqldb.model) self-declares its own
            -- columns — it has no auto-injected updated_by at all. ->>'key' on
            -- jsonb degrades to NULL when the key's absent instead of raising
            -- "record has no field", so this works for both table shapes
            -- without the function needing to know which one it's on.
            INSERT INTO "_audit_filer" ("table", row_id, changes, changed_by)
            VALUES (
                TG_TABLE_NAME,
                COALESCE(NEW.id, OLD.id),
                jsonb_build_object(
                    'before', CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE old_json END,
                    'after',  CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE new_json END
                ),
                -- updated_by first (an UPDATE's actor), then created_by (an
                -- INSERT sets only created_by, so audit rows for inserts used
                -- to record NULL — the row's creator was never captured).
                COALESCE(
                    new_json->>'updated_by', new_json->>'created_by',
                    old_json->>'updated_by', old_json->>'created_by'
                )
            );
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql
        ;

-- (schema) CREATE TABLE "filerfile" (16 fields)
CREATE TABLE IF NOT EXISTS "filerfile" (
    "id" UUID PRIMARY KEY DEFAULT arc_uuid_generate_v7(),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "created_by" TEXT,
    "updated_by" TEXT,
    "_state" INTEGER NOT NULL DEFAULT 0,
    "file_id" VARCHAR(32) NOT NULL UNIQUE,
    "storage" VARCHAR(255) NOT NULL DEFAULT 'local',
    "storage_key" VARCHAR(255) NOT NULL UNIQUE,
    "original_filename" VARCHAR(255) NOT NULL,
    "content_type" VARCHAR(127) NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "checksum" VARCHAR(64) NOT NULL,
    "private" BOOLEAN NOT NULL DEFAULT TRUE,
    "status" VARCHAR(255) NOT NULL DEFAULT 'pending',
    "deleted_at" TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS "idx_filerfile_checksum" ON "filerfile" ("checksum");
CREATE INDEX IF NOT EXISTS "idx_filerfile_status" ON "filerfile" ("status");
DROP TRIGGER IF EXISTS arc_set_updated_at ON "filerfile";
CREATE TRIGGER arc_set_updated_at BEFORE UPDATE ON "filerfile" FOR EACH ROW EXECUTE FUNCTION arc_set_updated_at();
DROP TRIGGER IF EXISTS arc_soft_delete_to_trash ON "filerfile";
CREATE TRIGGER arc_soft_delete_to_trash AFTER INSERT OR UPDATE ON "filerfile" FOR EACH ROW EXECUTE FUNCTION arc_soft_delete_to_trash();

-- (schema) filerfile: attach audit trigger
DROP TRIGGER IF EXISTS arc_audit_filer ON "filerfile";
CREATE TRIGGER arc_audit_filer AFTER INSERT OR UPDATE OR DELETE ON "filerfile" FOR EACH ROW EXECUTE FUNCTION arc_audit_filer();
